---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: cpu-on-demand
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: ${name}
    securityGroupSelector:
      karpenter.sh/discovery: ${name}
    tags:
      karpenter.sh/discovery: ${name}
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: cpu-spot
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: ${name}
    securityGroupSelector:
      karpenter.sh/discovery: ${name}
    tags:
      karpenter.sh/discovery: ${name}
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gpu
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: [
        "p2.xlarge",
        "p2.8xlarge",
      ]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
  labels:
    mydomain.com/gpu-type: p2
  taints:
    - key: nvidia.com/gpu
      value: "true"
      effect: NoSchedule
  provider:
    subnetSelector:
      karpenter.sh/discovery: ${name}
    securityGroupSelector:
      karpenter.sh/discovery: ${name}
    tags:
      karpenter.sh/discovery: ${name}
  ttlSecondsAfterEmpty: 30